//  HAGearHappyFox.h
//
//Copyright (c) 2014 HelpStack (http://helpstack.io)
//
//Permission is hereby granted, free of charge, to any person obtaining a cop
//of this software and associated documentation files (the "Software"), to deal
//in the Software without restriction, including without limitation the rights
//to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//copies of the Software, and to permit persons to whom the Software is
//furnished to do so, subject to the following conditions:
//
//The above copyright notice and this permission notice shall be included in
//all copies or substantial portions of the Software.
//
//THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
//THE SOFTWARE.

#import <Foundation/Foundation.h>
#import "HSGear.h"

/**
 `HSHappyFox` is a subclass of `HSGear` with methods for making fetch and post requests for tickets and Knowledge Based articles on
 
 HappyFox helpdesk solution. It requires an API Key and Authorization code for Authenticating from HappyFox. The API Key and
 
 Authentication code is available in the Integrations page of your HappyFox account under Manage. It can be generated by clicking on
 
 the API configure link.
 */

@interface HSHappyFoxGear : HSGear


///----------------------------------------------------------
/// @name Getting HappyFox Ticket and KB Articles Information
///----------------------------------------------------------

/**
 The section ID which contains the relevant KB Articles to be fetched. By default this property is nil and if section ID is not
 
 provided, the KB Articles of all sections will be fetched.
 */
@property (nonatomic, strong) NSString *hfSectionID;

///-------------------------------------------
/// @name Creating and Initializing HSHappyFox
///-------------------------------------------

/**
 Initializes a `HFHappyFox` object with the specified base URL.
 
 This is the designated initializer.
 
 @param instanceUrl The base URL used to initialize the RequestOperationManager
 @param api_key The API key as username required for authentication
 @param auth_code The Authentication code as password for authentication
 */
- (id)initWithInstanceUrl:(NSString *) instanceUrl apiKey:(NSString *)api_key authCode:(NSString *)auth_code priorityID: (NSString *)priority_ID categoryID: (NSString *) category_ID;


@end
