//
//  HAGearHappyFox.h
//  HelpApp
//
//  Created by Santhana Amuthan on 31/10/13.
//  Copyright (c) 2013 Anand. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "HSGear.h"

/**
 `HSHappyFox` is a subclass of `HSGear` with methods for making fetch and post requests for tickets and Knowledge Based articles on
 
 HappyFox helpdesk solution. It requires an API Key and Authorization code for Authenticating from HappyFox. The API Key and
 
 Authentication code is available in the Integrations page of your HappyFox account under Manage. It can be generated by clicking on
 
 the API configure link.
 */

@interface HSHappyFoxGear : HSGear


///----------------------------------------------------------
/// @name Getting HappyFox Ticket and KB Articles Information
///----------------------------------------------------------

/**
 The section ID which contains the relevant KB Articles to be fetched. By default this property is nil and if section ID is not
 
 provided, the KB Articles of all sections will be fetched.
 */
@property (nonatomic, strong) NSString *hfSectionID;

///-------------------------------------------
/// @name Creating and Initializing HSHappyFox
///-------------------------------------------

/**
 Initializes a `HFHappyFox` object with the specified base URL.
 
 This is the designated initializer.
 
 @param instanceUrl The base URL used to initialize the RequestOperationManager
 @param api_key The API key as username required for authentication
 @param auth_code The Authentication code as password for authentication
 */
- (id)initWithInstanceUrl:(NSString *) instanceUrl apiKey:(NSString *)api_key authoCode:(NSString *)auth_code priorityID: (NSString *)priority_ID categoryID: (NSString *) category_ID;


@end
